### ISSUE TITLE
Custom Levels won't load if CustomLevels folder has more than a few hundred maps (7000 for example)

### ISSUE THREAD

**Issue by darksidebv** [InnocentThief/Custom-Songs-Manager#42]
Self explanatory.

**Comment by InnocentThief** [comment]
Hello there
Can you please send me your application log (csm.log). You can find it under "C:\Users\InnocentThief\AppData\Roaming\Custom Songs Manager" (replace InnocentThief with your username). We tested with around 3000 maps and had no issues so far. There may be a problem after that amount of maps.

**Comment by darksidebv** [comment]
Hello. Here is the log file. I don't know if it is relevant but I have a bunch of maps that longer exist on beatsaver and some of them are from early 2019 before a newer song format was released, that is why I think the first lines of the log file refer to.

[csm.log](https://github.com/InnocentThief/Custom-Songs-Manager/files/10197609/csm.log)

**Comment by InnocentThief** [comment]
I'll have a look into it over the weekend. Looks like there is a value in the maps JSON that has a wrong format (not decimal).

The new maps normally start with the key in the beginning of the directory name. Old maps have an other folder name and as such CSM is not able to read them. Those lines in the log with the folder name are just for information. 

The real problem is the wrong format in the JSON file.

**Comment by InnocentThief** [comment]
Done in version 1.5.0.1
